server:
  port: 8085
spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  datasource:
    #1.JDBC
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/researchplatform?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
#    password: dreamtech1012
#    url: jdbc:mysql://39.99.152.97:3306/researchplatform?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #      filters: stat,wall,slf4j   注册p6spy要去掉防火墙wall
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        #允许那些ip
        allow: 127.0.0.1
        login-username: admin
        login-password: admin
        #禁止那些ip
        #        deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true
      filter:
        slf4j:
          statement-executable-sql-log-enable: true
      filters: stat,wall,slf4j
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  task:
    scheduling:
      shutdown:
        await-termination: true
        await-termination-period: 60s
      pool:
        size: 2
      thread-name-prefix: 定时任务
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  sql:
    init:
      mode: always
mybatis:
  configuration:
    local-cache-scope: statement
    map-underscore-to-camel-case: true
customize:
  rank-size: 50
  save-location: ${user.home}
  retain-day: 15
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    cn:
      edu:
        ncepu:
          researchplatform:
            mapper: debug
---
spring:
  config:
    activate:
      on-profile: pro
logging:
  level:
    root: warn


