server:
  port: 8085
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://202.206.212.65:3306/researchplatform?useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource